name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Carbon markdown
        id: carbon-markdown
        uses: ./
        with:
          carbonConfigFile: carbon-config.json
          defaultCarbonPreset: default

      - name: Auto-commit
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.md carbon'
          commit_message: 🤖 Commiting carbon-now changes
